<!ELEMENT auton (zone) >

<!ELEMENT zone EMPTY >
<!ATTLIST zone

    x1_rect CDATA #IMPLIED
    y1_rect CDATA #IMPLIED
    x2_rect CDATA #IMPLIED
    y2_rect CDATA #IMPLIED

    circlex                 CDATA #IMPLIED
    circley                 CDATA #IMPLIED
    radius                  CDATA #IMPLIED                

    pathUpdateOption 	    ( DRIVE_TO_HUB | DRIVE_OVER_BUMP | DRIVE_TO_DEPOT | DRIVE_TO_OUTPOST | DRIVE_TO_TOWER | NOTHING ) "NOTHING"         

    allianceColor ( RED | BLUE | BOTH ) "BOTH"


    
>


